sudo: false

services:
  - docker

before_script:
  - docker -v
  - docker build -t my-component .

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
