sudo: false

services:
  - docker

before_script:
  - docker -v
  - docker build -t my-component .

script:
  - docker run my-component /code/run_tests.sh || echo "TESTS FAILED"

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
